# 服务端口
server:
  port: 8080

# 配置rabbitmq服务
spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    # host: 159.75.4.236
    # port: 5672
    publisher-confirm-type: correlated
    addresses: 159.75.4.236:5672